# Generated by Django 5.2 on 2026-04-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_actors_country_genres_languages_comments_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='comments',
            field=models.ManyToManyField(blank=True, to='movie_app.comments'),
        ),
    ]
